// DO NOT EDIT THIS FILE !

const path = require('path')
const express = require('express')
const { Server } = require('ws')

const port = process.env.PORT || 3000

// Express

const app = express()

app.use(express.static(path.resolve(__dirname, 'public')))

// WebSocket

const wss = new Server({
  server: app.listen(port)
})

let connections = []

wss.on('connection', ws => {
  connections.push(ws)

  ws.on('close', () => {
    connections = connections.filter(connection => !(connection === ws))
  })

  ws.on('message', message => {
    connections.forEach(connection => connection.send(message))
  })
})

// Log

console.log(`Listening on localhost:${port}`)
